apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-lab
spec:
  selector:
    matchLabels:
      app: argocd-lab
  replicas: 3
  template:
    metadata:
      labels:
        app: argocd-lab
    spec:
      containers:
      - name: argocd-lab
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
